### ISSUE TITLE
The initial version should be `0.1.0`

### ISSUE THREAD

**Issue by justinmchase** [dylanpyle/version#5]
When running `version init` it should default to `0.1.0` and it should probably support an optional argument which would allow a different initial version.

Arguably it could be `0.0.0` but `1.0.0` is probably too aggressive. `1.0.0` should be reserved for the first production ready version.

**Comment by dylanpyle** [comment]
Ooh, hot take! I chose 1.0.0 mostly because (a) that's what npm does, and (b) I _personally_ don't use 0.x.x versions in my own projects, but I understand there are good arguments for/against. Maybe just a new argument e.g `version init 0.1.0`?

**Comment by dylanpyle** [comment]
Reference points:

- [The "Semantic Versioning Standard" recommends 0.1.0](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
- [npm specifically decided against it](https://github.com/npm/init-package-json/issues/35)

Anyway I'm _lightly_ coming down on the side of "I'd rather keep 1.0.0 the default" because I also don't love the number of projects _which I use in production_ which still claim to be 0.x.x. But absolutely open to configurability here.

**Comment by dylanpyle** [comment]
(Closing since #9 makes this configurable)

**Comment by justinmchase** [comment]
It seems like the logic for why npm didn't follow semver is all oriented around `^` and version ranges, which isn't even supported in deno at all, you have to specify a version specific... I think that is one of the major areas of problematic complexity in node that Deno just fixed by design up front.

Configurability helps a lot though.
